---
- name: Provision the server
  hosts: localhost
  tags: always
  vars_files:
    - config.cfg
    - config.newtroy.cfg
    - config.newtroy.vault.cfg

  pre_tasks:
    - block:
      - name: Local pre-tasks
        import_tasks: playbooks/cloud-pre.yml
        tags: always
      rescue:
        - debug: var=fail_hint
          tags: always
        - fail:
          tags: always

  roles:
    # Run this role first to set client IP addresses early
    # TODO: Switch away from old-style tags for new-style vars
    - role: dns_vpn_internal_network_route53
      tags: ['dns_vpn_internal_network_route53']

    - role: cloud-digitalocean
      when: algo_provider == "digitalocean"
    - role: cloud-ec2
      when: algo_provider == "ec2"
    - role: cloud-vultr
      when: algo_provider == "vultr"
    - role: cloud-gce
      when: algo_provider == "gce"
    - role: cloud-azure
      when: algo_provider == "azure"
    - role: cloud-lightsail
      when: algo_provider == "lightsail"
    - role: cloud-scaleway
      when: algo_provider == "scaleway"
    - role: cloud-openstack
      when: algo_provider == "openstack"
    - role: local
      when: algo_provider == "local"

    # Ensure this role comes after the deployment -
    # it relies on the VPN server being deployed
    # TODO: Switch away from old-style tags for new-style vars
    - role: dns_vpn_server_route53
      tags: ['dns_vpn_server_route53'] }

  post_tasks:
    - block:
      - name: Local post-tasks
        import_tasks: playbooks/cloud-post.yml
        become: false
        tags: cloud
      rescue:
        - debug: var=fail_hint
          tags: always
        - fail:
          tags: always
