---

- name: Ask user for the input
  hosts: localhost
  tags: always
  vars_files:
    - config.cfg

  tasks:

    - pause:
      prompt: |
        Enter the public IP address or domain name of your server: (IMPORTANT! This is used to verify the certificate)
      register: _endpoint
      when: endpoint is undefined

    - name: Set the facts
      set_fact:
        IP_subject_alt_name: >-
          {% if endpoint is defined %}{{ endpoint }}
          {%- elif _endpoint.user_input is defined and _endpoint.user_input != "" %}{{ _endpoint.user_input }}
          {%- else %}{{ cloud_instance_ip }}{% endif %}
