#!/bin/sh
set -eu

# Deploy NEWTROY
#
# Tags:
# 1. ec2:               required for AWS
# 2. vpn:               required for any Algo deployment
# 3. cloud:             required for non-local deployments (I think?)
# 4. security:          make additional security enhancements
# 5. encrypted:         encrypt the AWS EBS volume
# 6. ssh_tunneling:     enable SSH tunneling, and save configs/known_hosts
# 7. dns_route53:       enable route53 DNS
#
# Note that a typical Algo deployment passes in multiple variables with `-e` on the command line,
# but since this is a fork containing just my configuration,
# I have set those values in config.cfg and config.vault.cfg
# (See README.NEWTROY.md for more information)

ansible-playbook deploy.yml -t ec2,vpn,cloud,security,encrypted,ssh_tunneling,dns_route53
