---

- name: Update Route53

  route53:
    aws_access_key: "{{ aws_access_key | default(lookup('env','AWS_ACCESS_KEY_ID'), true)}}"
    aws_secret_key: "{{ aws_secret_key | default(lookup('env','AWS_SECRET_ACCESS_KEY'), true)}}"
    #region: "{{ region }}"
    overwrite: yes
    retry_interval: 15
    hosted_zone_id: "{{ vpn_hosted_zone_id }}"
    zone: "{{ vpn_domain }}"
    record: "{{ item.1 }}.{{ vpn_domain }}"
    type: A
    ttl: 300
    value: "{{ vpn_network | ipaddr(item.0 + 1) | ipaddr('address') }}"
    command: create
    # Waiting could take 40 (or more?) seconds PER RECORD, so you might not want this
    wait: yes

  # when using a with_indexed_items loop:
  # - {{ item.0 }} is the index, starting from zero
  # - {{ item.1 }} is the value
  with_indexed_items: "{{ users }}"

  when:
  - vpn_domain is defined
  - vpn_hosted_zone_id is defined
