---

- name: Encrypt the configs directory
  shell: >
    tar -c "configs" |
      gzip |
      gpg --recipient "{{ newtroy_encryption_recipient }}" --encrypt --output "{{ newtroy_encrypted_configs }}"

- debug:
    msg: |
      The contents of the configs/ directory has been encrypted for {{ newtroy_encryption_recipient }}
      and the results saved to {{ newtroy_encrypted_configs }}
